name: ci-fullstack-workflow

# Ensure the workflow runs on schedule (Sunday at 0:00) and on push to the main branch
on: 
  push:
    branches:
      - main
  schedule:
      - cron: "0 0 * * SUN"
    
  

#Use a matrix strategy to use Node.js versions 16.x and 18.x
jobs:
  build:
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [16,18]

    steps:
      # Check out the code from the repository. 
      - uses: actions/checkout@v4
      # Set up a Node.js environment using the specified node version.
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Install the dependencies.
      - run: |
        cd backend
        npm install

      # Run the tests.
      - run: npm test

      # Run the linter.
      - run: npm lint

      # Send a console message at completion.
      - run: |
          echo "Hello ${{github.actor}}. You pushed to ${{github.repository}} at $(date)."

        
